name: pardakht_parto
description: پرداخت پرتو

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  adobe_xd: ^2.0.0+1
  shared_preferences: ^2.0.6
  device_info: ^2.0.2
  http: ^0.13.3
  flutter_money_formatter: ^0.8.3
  contact_picker: ^0.0.2
  persian_datepicker: ^1.3.1
  intl: ^0.15.8
  otp_count_down: ^1.0.6
  url_launcher: ^6.0.6
  sentry_flutter: ^5.1.0
  flutter_barcode_scanner: ^2.0.0
  qr_utils: ^0.1.5
  material_design_icons_flutter: ^4.0.5955
  image_picker_saver: ^0.3.0
  firebase_messaging: ^10.0.2
  root_access: ^1.0.4
  check_vpn_connection: ^0.0.1
  package_info: ^2.0.2
  uni_links2: ^0.6.0+2
  connectivity: ^3.0.6
  flutter_local_notifications: ^6.0.0
  modal_progress_hud: ^0.1.3
  share: ^2.0.4
  share_files_and_screenshot_widgets: ^1.0.4
  overlay_support: ^1.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  fonts:
    - family: IRANSans(FaNum)
      fonts:
        - asset: assets/fonts/IRANSans(FaNum).ttf
        - asset: assets/fonts/IRANSans(FaNum)_UltraLight.ttf
          weight: 100
        - asset: assets/fonts/IRANSans(FaNum)_Light.ttf
          weight: 300
        - asset: assets/fonts/IRANSans(FaNum)_Medium.ttf
          weight: 500
        - asset: assets/fonts/IRANSans(FaNum)_Bold.ttf
          weight: 700
    - family: Dirooz
      fonts:
        - asset: assets/fonts/Dirooz.ttf

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/images/RegisterFooterImg.png
    - assets/images/home.png
    - assets/images/wallet.png
    - assets/images/mtn-color.jpg
    - assets/images/mtn-gray.jpg
    - assets/images/rightel-color.jpg
    - assets/images/rightel-gray.jpg
    - assets/images/shatel-color.jpg
    - assets/images/shatel-gray.jpg
    - assets/images/mci-color.jpg
    - assets/images/mci-gray.jpg
    - assets/images/man.png
    - assets/images/woman.png
    - assets/images/3g4g5g.png
    - assets/images/charge.png
    - assets/images/sim-Charge.png
    - assets/images/ghobooz3.png
    - assets/images/logo/Ab-color.jpg
    - assets/images/logo/Bargh-gray.jpg
    - assets/images/logo/gaz-color.jpg
    - assets/images/logo/maliat-gray.jpg
    - assets/images/logo/Bargh-color.jpg
    - assets/images/logo/maliat-color.jpg
    - assets/images/logo/rahvar-gray2.jpg
    - assets/images/logo/mokhaberat-color.jpg
    - assets/images/logo/rahvar-color.jpg
    - assets/images/logo/mokhaberat-grayr.jpg
    - assets/images/logo/Ab-gray.jpg
    - assets/images/logo/gaz-gray.jpg
    - assets/images/logo/shahrdary-gray.jpg
    - assets/images/logo/shahrdary-color.jpg
    - assets/images/Donation.png
    - assets/images/internet.png
    - assets/images/donation2.png
    - assets/images/4GPackages.png
    - assets/images/wallet-png.png
    - assets/logo.png
